#默认使用配置
spring:
  profiles:
    active: dev
#公共配置与profiles选择无关
server:
  port: 8080
  context-path: /mms 
---
#开发配置
spring:
  profiles: dev
  datasource:
    name: mysql
    #url: jdbc:postgresql://localhost:5432/mms 
    #username: lkh
    #password: sa
    url: jdbc:mysql://localhost:3306/mms
    username: root
    password: 1234
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: org.postgresql.Driver
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  typeAliasesPackage: com.mms.model
  mapperLocations: classpath:mapping/*.xml
#pagehelper分页插件
pagehelper:
    #helperDialect: PostgreSQL
    helperDialect: MySQL
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql