package com.mms.model;

import java.io.Serializable;
import java.util.Date;

public class Orgs implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_org_t.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_org_t.parent_org_id
     *
     * @mbggenerated
     */
    private Long parentOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_org_t.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_org_t.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_org_t.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mms_org_t
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_org_t.org_id
     *
     * @return the value of mms_org_t.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_org_t.org_id
     *
     * @param orgId the value for mms_org_t.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_org_t.parent_org_id
     *
     * @return the value of mms_org_t.parent_org_id
     *
     * @mbggenerated
     */
    public Long getParentOrgId() {
        return parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_org_t.parent_org_id
     *
     * @param parentOrgId the value for mms_org_t.parent_org_id
     *
     * @mbggenerated
     */
    public void setParentOrgId(Long parentOrgId) {
        this.parentOrgId = parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_org_t.org_name
     *
     * @return the value of mms_org_t.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_org_t.org_name
     *
     * @param orgName the value for mms_org_t.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_org_t.description
     *
     * @return the value of mms_org_t.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_org_t.description
     *
     * @param description the value for mms_org_t.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_org_t.create_time
     *
     * @return the value of mms_org_t.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_org_t.create_time
     *
     * @param createTime the value for mms_org_t.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}