package com.mms.model;

import java.io.Serializable;
import java.util.Date;

public class Rights implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_right_t.right_id
     *
     * @mbggenerated
     */
    private Long rightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_right_t.parent_right_id
     *
     * @mbggenerated
     */
    private Long parentRightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_right_t.right_name
     *
     * @mbggenerated
     */
    private String rightName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_right_t.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_right_t.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mms_right_t
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_right_t.right_id
     *
     * @return the value of mms_right_t.right_id
     *
     * @mbggenerated
     */
    public Long getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_right_t.right_id
     *
     * @param rightId the value for mms_right_t.right_id
     *
     * @mbggenerated
     */
    public void setRightId(Long rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_right_t.parent_right_id
     *
     * @return the value of mms_right_t.parent_right_id
     *
     * @mbggenerated
     */
    public Long getParentRightId() {
        return parentRightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_right_t.parent_right_id
     *
     * @param parentRightId the value for mms_right_t.parent_right_id
     *
     * @mbggenerated
     */
    public void setParentRightId(Long parentRightId) {
        this.parentRightId = parentRightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_right_t.right_name
     *
     * @return the value of mms_right_t.right_name
     *
     * @mbggenerated
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_right_t.right_name
     *
     * @param rightName the value for mms_right_t.right_name
     *
     * @mbggenerated
     */
    public void setRightName(String rightName) {
        this.rightName = rightName == null ? null : rightName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_right_t.description
     *
     * @return the value of mms_right_t.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_right_t.description
     *
     * @param description the value for mms_right_t.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_right_t.create_time
     *
     * @return the value of mms_right_t.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_right_t.create_time
     *
     * @param createTime the value for mms_right_t.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}