package com.mms.model;

import java.io.Serializable;
import java.util.Date;

public class Roles implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_role_t.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_role_t.parent_role_id
     *
     * @mbggenerated
     */
    private Long parentRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_role_t.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_role_t.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_role_t.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mms_role_t
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_role_t.role_id
     *
     * @return the value of mms_role_t.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_role_t.role_id
     *
     * @param roleId the value for mms_role_t.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_role_t.parent_role_id
     *
     * @return the value of mms_role_t.parent_role_id
     *
     * @mbggenerated
     */
    public Long getParentRoleId() {
        return parentRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_role_t.parent_role_id
     *
     * @param parentRoleId the value for mms_role_t.parent_role_id
     *
     * @mbggenerated
     */
    public void setParentRoleId(Long parentRoleId) {
        this.parentRoleId = parentRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_role_t.role_name
     *
     * @return the value of mms_role_t.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_role_t.role_name
     *
     * @param roleName the value for mms_role_t.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_role_t.description
     *
     * @return the value of mms_role_t.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_role_t.description
     *
     * @param description the value for mms_role_t.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_role_t.create_time
     *
     * @return the value of mms_role_t.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_role_t.create_time
     *
     * @param createTime the value for mms_role_t.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}