package com.mms.model;

import java.io.Serializable;
import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
@ApiModel("输出用户数据的类")
public class Users implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.password
     *
     * @mbggenerated
     */
    @ApiModelProperty(required=true,value="登录的密码")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.vsername
     *
     * @mbggenerated
     */
    private String vsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.email
     *
     * @mbggenerated
     */
    @ApiModelProperty(required=true,value="登录的邮箱地址")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_user_t.login_count
     *
     * @mbggenerated
     */
    private Long loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mms_user_t
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.user_id
     *
     * @return the value of mms_user_t.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.user_id
     *
     * @param userId the value for mms_user_t.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.org_id
     *
     * @return the value of mms_user_t.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.org_id
     *
     * @param orgId the value for mms_user_t.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.login_name
     *
     * @return the value of mms_user_t.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.login_name
     *
     * @param loginName the value for mms_user_t.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.password
     *
     * @return the value of mms_user_t.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.password
     *
     * @param password the value for mms_user_t.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.vsername
     *
     * @return the value of mms_user_t.vsername
     *
     * @mbggenerated
     */
    public String getVsername() {
        return vsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.vsername
     *
     * @param vsername the value for mms_user_t.vsername
     *
     * @mbggenerated
     */
    public void setVsername(String vsername) {
        this.vsername = vsername == null ? null : vsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.phone
     *
     * @return the value of mms_user_t.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.phone
     *
     * @param phone the value for mms_user_t.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.email
     *
     * @return the value of mms_user_t.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.email
     *
     * @param email the value for mms_user_t.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.create_time
     *
     * @return the value of mms_user_t.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.create_time
     *
     * @param createTime the value for mms_user_t.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.login_time
     *
     * @return the value of mms_user_t.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.login_time
     *
     * @param loginTime the value for mms_user_t.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.last_login_time
     *
     * @return the value of mms_user_t.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.last_login_time
     *
     * @param lastLoginTime the value for mms_user_t.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_user_t.login_count
     *
     * @return the value of mms_user_t.login_count
     *
     * @mbggenerated
     */
    public Long getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_user_t.login_count
     *
     * @param loginCount the value for mms_user_t.login_count
     *
     * @mbggenerated
     */
    public void setLoginCount(Long loginCount) {
        this.loginCount = loginCount;
    }
}