package com.mms.mapper;

import com.mms.model.Orgs;

public interface OrgsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_org_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_org_t
     *
     * @mbggenerated
     */
    int insert(Orgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_org_t
     *
     * @mbggenerated
     */
    int insertSelective(Orgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_org_t
     *
     * @mbggenerated
     */
    Orgs selectByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_org_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Orgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_org_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Orgs record);
}