package com.mms.mapper;

import com.mms.model.Roles;

public interface RolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_role_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_role_t
     *
     * @mbggenerated
     */
    int insert(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_role_t
     *
     * @mbggenerated
     */
    int insertSelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_role_t
     *
     * @mbggenerated
     */
    Roles selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_role_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_role_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Roles record);
}