package com.mms.mapper;

import java.util.List;

import com.mms.model.Users;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_user_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_user_t
     *
     * @mbggenerated
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_user_t
     *
     * @mbggenerated
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_user_t
     *
     * @mbggenerated
     */
    List<Users> selectUserBySearch(Users user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_user_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_user_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Users record);
}